version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: api/Docker/Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
    environment:
      - GO_ENV=development
  frontend:
    build:
      context: .
      dockerfile: frontend/Docker/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./frontend:/app/src/node_modules
    command: bash -c "yarn dev"
    environment:
      - NODE_ENV=development
