# .air.toml
root = "."
tmp_dir = "./air/tmp"

[build]
  cmd = "go build -o ./air/tmp/main ."
  bin = "./air/tmp/main"
  exclude_dir = ["assets", "tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  delay = 1000

[log]
  time = true
