FROM golang:1.21-alpine

RUN apk update && \
    apk add bash && \
    apk add alpine-sdk && \
    apk add curl && \
    curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1

WORKDIR /app

COPY api/src/air/.air.toml ./air
COPY api/src/go.mod ./
COPY api/src/go.sum ./

WORKDIR /app/src

ENV GO111MODULE=on
RUN go mod download

RUN go install github.com/cosmtrek/air@latest
CMD ["air", "-c", "air/.air.toml"]
